services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}